### PR TITLE
chore: install githooks via the entrypoint

### LINKED ISSUE #117: enable renku git hooks on project clone
The entrypoint should contain a call to `renku` to install the git hooks in the project at launch time. It's not nice to do this in the init container because it's renku version-dependent so it's best to do it in the entrypoint to keep it consistent with the renku installed in the users environment.

### PR DESCRIPTION
**Pull request by rokroskar**
addresses #118
closes #117

### CODE REVIEW

**Review by ableuler — APPROVED** [review]
Didn't test this, but seems straightforward and makes sense.

**Comment by rokroskar** [comment]
The only thing we may want to do is to make it

```
renku githooks install || true
```

so that if for some reason the user has some bizarre renku version installed that messes up this command it doesn't prevent the container from starting.

**Comment by rokroskar** [comment]
Ok I've tested it now and this works.

**Review by ableuler — APPROVED** [review]

**Review by ableuler — COMMENTED** [review]
Actually, don't our other images (like the Rstudio one) overwrite the entrypoint?

**Comment by rokroskar** [comment]
🤦 yes, you're right... I'll make the same change to the otheres

**Review by ableuler — APPROVED** [review]

**Comment by ableuler** [comment]
@rokroskar can this one be merged?

**Comment by rokroskar** [comment]
I believe so

**Pull request merged**
