### PR TITLE
docs: Update README.md

### LINKED ISSUE #159: improve the description of available versions in the README
It's not very easy to discover the available versions of images from our README - we should have a table of some sort that outlines the tags that people can look for (maybe with links to docker hub?)

### PR DESCRIPTION
**Pull request by gavin-k-lee**
fixes #159

### CODE REVIEW

**Comment by rokroskar** [comment]
Thanks for this @gavin-k-lee - note that the `renku/renkulab-cuda-tf` image is what should be used for GPU work - I think we can remove mention of the other cuda images.

**Comment by gavin-k-lee** [comment]
Alright. Should we then also remove the Cuda 9.2 builds from the GH action?

**Comment by rokroskar** [comment]
Probably - I thought I had done that already but apparently not 🙈

**Comment by gavin-k-lee** [comment]
I've removed the Cuda 9.2 references and cleaned up some of the md file

**Review by rokroskar — APPROVED** [review]
🚀 Thanks!!

**Pull request merged**
