### PR TITLE
fix: add renku cli to PATH in rstudio

### PR DESCRIPTION
**Pull request by olevski**
Fixes renku not being present in the PATH of rstudio images.

### CODE REVIEW

**Comment by olevski** [comment]
This project: https://renkulab.io/projects/tasko.olevski/test-r-project-1 uses the image built in this repo. And renku cli works in both rstudio and jupyterlab.

**Comment by rokroskar** [comment]
if I'm reading the R Dockerfile correctly, we never actually install renku in there. Should we copy it from the python base image like we do the other python packages [here](https://github.com/SwissDataScienceCenter/renkulab-docker/blob/master/docker/r/Dockerfile#L75-L80)? I guess all that is needed is something like 

```
COPY --from renku_base /home/jovyan/.renku /home/rstudio/.renku
```

**Comment by olevski** [comment]
> if I'm reading the R Dockerfile correctly, we never actually install renku in there. Should we copy it from the python base image like we do the other python packages [here](https://github.com/SwissDataScienceCenter/renkulab-docker/blob/master/docker/r/Dockerfile#L75-L80)? I guess all that is needed is something like
> 
> ```
> COPY --from renku_base /home/jovyan/.renku /home/rstudio/.renku
> ```

Rok what you describe does happen in the Dockerfile here: https://github.com/SwissDataScienceCenter/renkulab-docker/pull/232/files#diff-0905cf205d369bd74981475a9ea32b552da07810e4010c9936058a9837a6885eR79.

Maybe I misunderstand what you mean though.

**Comment by gavin-k-lee** [comment]
I verified that the cli is available in that image :+1:

**Comment by rokroskar** [comment]
@olevski you're totally right I missed it because of the line break 🤦 !!

**Comment by olevski** [comment]
@rokroskar @gavin-k-lee if you are done testing/reviewing can you approve please?

**Review by rokroskar — APPROVED** [review]

**Pull request merged**
