### PR TITLE
feat: add bioc 3.16 and 3.17 to matrix

### PR DESCRIPTION
**Pull request by rokroskar**
Adds bioconductor 3.16 to the build matrix.

### CODE REVIEW

**Comment by olevski** [comment]
@rokroskar I tested both the 3.16 and 3.17 bioconductor images. After the fix you added in the entrypoint (which we already merged) things work normally. So this can be merged.

**Comment by olevski** [comment]
If you merge this I will make a release.

**Comment by rokroskar** [comment]
perfect, thank you!

**Comment by rokroskar** [comment]
> If you merge this I will make a release.

That would be great - I guess it can be `0.15.1`

**Pull request merged**
