### PR TITLE
chore: update rstudio version

### PR DESCRIPTION
**Pull request by olevski**
I still have to test this to see if it works and fixes the issue reported here:
https://renku.discourse.group/t/rstudio-version-too-old/393

### CODE REVIEW

**Comment by olevski** [comment]
No luck with a quick PR. Rstudio does not start with this change. So we need to do some troubleshooting.

**Comment by TaoSunVoyage** [comment]
this is related to #154 and #160

**Review by ableuler — APPROVED** [review]
as far as I can tell from running the resulting image locally, this should solve the problem reported in the discourse post.

**Comment by TaoSunVoyage** [comment]
thanks @ableuler. 

Bioconductor 3.13 requires R 4.10. R 4.1.0 can only work in RStudio 1.4 #160. However, there are still some issues with `jupyter-rsession-proxy`. Although it works locally, this extension doesn't seem to function very well in JupyterHub (see my comments [here](https://github.com/SwissDataScienceCenter/renkulab-docker/issues/154#issuecomment-901199983))

**Comment by ableuler** [comment]
> thanks @ableuler.
> 
> Bioconductor 3.13 requires R 4.1.0, which can only work in RStudio 1.4 #160. However, there are still some issues with `jupyter-rsession-proxy`. Although it works locally, this extension doesn't seem to function very well in JupyterHub (see my comments [here](https://github.com/SwissDataScienceCenter/renkulab-docker/issues/154#issuecomment-901199983))

Ah sorry, hadn't seen your comment on the issue. I just had a quick look why acceptance tests on this PR were failing and fixed it by adjusting the `www-root-path` manually or setting `RSESSION_PROXY_RSTUDIO_1_4=true` respectively.

**Comment by rokroskar** [comment]
So does this work or not?

**Comment by TaoSunVoyage** [comment]
> So does this work or not?

not yet

**Review by rokroskar — CHANGES_REQUESTED** [review]
lets make sure it works :)

**Comment by rokroskar** [comment]
ok - I was confused by all the green and was tempted to push the merge button 😆

**Comment by ableuler** [comment]
Yeah - I think in the light of recent events and our future plans for Rstudio sessions in renkulab.io, I'd suggest to close this PR altogether.

**Pull request closed without merging**
