### PR TITLE
chore: update jupyter base

### PR DESCRIPTION
**Pull request by rokroskar**
Updates the base image to an updated jupyter base-notebook image which means a different version of ubuntu and python.

To verify:

- [x] python image
- [x] R image
- [x] cuda

### CODE REVIEW

**Comment by ableuler** [comment]
python image seems to work fine!

**Comment by olevski** [comment]
@rokroskar I can confirm that the fix for the cuda-tf image works.

One thing I saw is that the cuda.9.2 image (without tensorflow) is not part of the makefile. Should we fully get rid of this? Or I think it may be better to include the part that installs cuda from the cuda-tf image and make it a standalone cuda image without tf? Then the cuda-tf image can start with the cuda-only image. And the cuda-only image can be there for anyone who needs it - i.e. people who use pytorch.

**Comment by rokroskar** [comment]
Thanks for checking @olevski! Good point about cuda-9.2 - afaik no one uses that anymore so we should remove it, but lets do it in a follow-up PR

**Comment by rokroskar** [comment]
actually I didn't fully read what you wrote :)  Also +1 on having a cuda image without TF.

**Review by olevski — APPROVED** [review]

**Comment by olevski** [comment]
Here is a new issue for the cuda without tensorflow image: https://github.com/SwissDataScienceCenter/renkulab-docker/issues/141

**Pull request merged**
