### PR TITLE
chore: disable jupyter announcement plugin

### PR DESCRIPTION
**Pull request by rokroskar**
This prevents the pop up about jupyter announcements.

### CODE REVIEW

**Review by olevski — APPROVED** [review]
That is awesome Rok! Thank you.

I do not see the notification anymore.

**Comment by rokroskar** [comment]
I just realized we need to do the same in the other base images... 😆

**Comment by olevski** [comment]
@rokroskar I will open a PR for this.

**Comment by rokroskar** [comment]
@olevski that would be great, thanks!!

**Comment by olevski** [comment]
The change in the base image trickles to all the other images. This is fully resolved.

**Pull request merged**
