### PR TITLE
chore(build): add bioc 3.12

### PR DESCRIPTION
**Pull request by rokroskar**

### CODE REVIEW

**Comment by rokroskar** [comment]
This was on hold because bioconductor had not actually released the 3.12 docker images yet but now they seem to be there so please review

**Comment by olevski** [comment]
👍

**Review by olevski — APPROVED** [review]

**Comment by rokroskar** [comment]
I think something is weird with this PR - it's also not telling me to update the branch even though it's clearly behind master...

**Comment by rokroskar** [comment]
ah there we go, now it's green 👍

**Pull request merged**
